### PR TITLE
Big new update

### PR DESCRIPTION
**Pull request by Satttoshi**
pls check

### CODE REVIEW

**Comment by Satttoshi** [comment]
^Click on "View Deployment" to have a Web view of html

**Review by FrankSiyli — APPROVED** [review]
LGTM✌️

**Review by DominicWebDev — APPROVED** [review]
good job, more cat picture pls

**Review by UnamGitHub — APPROVED** [review]
well done, lgtm 👍

**Review by toshydev — APPROVED** [review]
Love it! 
Early cat catches the fish.
LGTM! 💪

**Pull request merged**
